### ISSUE TITLE
Error when restarting HA and tv is off

### ISSUE THREAD

**Issue by Stefos13** [jaruba/ha-samsungtv-custom#18]
So I upgraded to 0.105.2 and i noticed a weird behavior. If I restart my HA and my TV is turned off it doesn't show as an entity and i'm getting the following error:
`custom_components/samsungtv_custom/samsungtvws/remote.py (ERROR) 

 `Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 774, in capability_attributes
    source_list = self.source_list
  File "/config/custom_components/samsungtv_custom/media_player.py", line 319, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_custom/media_player.py", line 229, in _gen_installed_app_list
    app_list = self._remote.app_list()
  File "/config/custom_components/samsungtv_custom/samsungtvws/remote.py", line 179, in app_list
    self._ws_send(payload)
  File "/config/custom_components/samsungtv_custom/samsungtvws/remote.py", line 93, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_custom/samsungtvws/remote.py", line 108, in open
    sslopt=sslopt
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 511, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 186, in _open_socket
    raise error
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
socket.timeout: timed out`

Now if i restart HA and my tv is turned on i'm getting this warning 

`helpers/entity.py (WARNING)
Updating state for media_player.living_room_tv (<class 'custom_components.samsungtv_custom.media_player.SamsungTVDevice'>) took 0.616 seconds.`

Anyone with similar problem?

**Comment by jaruba** [comment]
Read this: https://github.com/jaruba/ha-samsungtv-custom/issues/17

**Comment by jaruba** [comment]
I added `websocket-client==0.57.0` to requirements.
